'use client';

import { DndContext, KeyboardSensor, PointerSensor, closestCenter, useSensor, useSensors, type DragEndEvent } from '@dnd-kit/core';
import { SortableContext, arrayMove, sortableKeyboardCoordinates, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { GripVertical, Plus, Trash2 } from 'lucide-react';
import type { EducationEntry, ExperienceProject, InternshipEntry, ResumeModule, RichTextContent } from '@/src/schema/types';
import { richText, getRichTextPlainText } from '@/src/schema/richtext';
import { RichTextEditor } from '@/src/richtext/rich-text-editor';
import { ContentBlocksEditor } from '@/src/editor/content-block-editor';
import { useResumeStore } from '@/src/store/provider';

function RichField({ label, content, onChange }: { label: string; content?: RichTextContent; onChange: (value: RichTextContent) => void }) {
  return <label className="rich-field"><span className="field-label">{label}</span><RichTextEditor ariaLabel={label} compact content={content ?? richText('')} onChange={onChange} /></label>;
}

function DateFields({ value, onChange }: { value: { startDate?: string; endDate?: string; current?: boolean }; onChange: (next: { startDate?: string; endDate?: string; current?: boolean }) => void }) {
  return <div className="date-fields"><label><span>开始日期</span><input type="month" value={value.startDate ?? ''} onChange={(event) => onChange({ ...value, startDate: event.target.value })} /></label><label><span>结束日期</span><input type="month" disabled={value.current} value={value.endDate ?? ''} onChange={(event) => onChange({ ...value, endDate: event.target.value })} /></label><label className="current-check"><input type="checkbox" checked={value.current ?? false} onChange={(event) => onChange({ ...value, current: event.target.checked, endDate: event.target.checked ? undefined : value.endDate })} /><span>至今</span></label></div>;
}

function SortableEntry({ id, label, children, onDelete }: { id: string; label: string; children: React.ReactNode; onDelete: () => void }) {
  const sortable = useSortable({ id });
  return <article ref={sortable.setNodeRef} style={{ transform: CSS.Transform.toString(sortable.transform), transition: sortable.transition }} className="entry-editor-card"><header><button className="drag-button" aria-label={`拖动${label}`} {...sortable.attributes} {...sortable.listeners}><GripVertical size={15} /></button><strong>{label}</strong><button aria-label={`删除${label}`} onClick={onDelete}><Trash2 size={14} /></button></header>{children}</article>;
}

function SortableEntries<T extends { id: string }>({ items, onChange, render }: { items: T[]; onChange: (items: T[]) => void; render: (item: T, index: number) => React.ReactNode }) {
  const sensors = useSensors(useSensor(PointerSensor), useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates }));
  const end = ({ active, over }: DragEndEvent) => { if (!over || active.id === over.id) return; const from = items.findIndex((item) => item.id === active.id); const to = items.findIndex((item) => item.id === over.id); if (from >= 0 && to >= 0) onChange(arrayMove(items, from, to)); };
  return <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={end}><SortableContext items={items.map((item) => item.id)} strategy={verticalListSortingStrategy}>{items.map(render)}</SortableContext></DndContext>;
}

function ProjectEditor({ project, onChange, onDelete, index }: { project: ExperienceProject; onChange: (project: ExperienceProject) => void; onDelete: () => void; index: number }) {
  return <SortableEntry id={project.id} label={`项目 ${index + 1}`} onDelete={onDelete}>
    <div className="rich-field-grid"><RichField label="项目名称" content={project.name} onChange={(name) => onChange({ ...project, name })} /><RichField label="职责" content={project.role} onChange={(role) => onChange({ ...project, role })} /><RichField label="其他信息" content={project.otherInfo} onChange={(otherInfo) => onChange({ ...project, otherInfo })} /></div>
    <DateFields value={project} onChange={(date) => onChange({ ...project, ...date })} />
    <ContentBlocksEditor blocks={project.blocks} onChange={(blocks) => onChange({ ...project, blocks })} />
  </SortableEntry>;
}

function ProfileEditor({ module, update }: { module: Extract<ResumeModule, { type: 'profile' }>; update: (module: ResumeModule) => void }) {
  const uploadPhoto = (file?: File) => { if (!file || !/^image\/(jpeg|png|webp)$/.test(file.type)) return; const reader = new FileReader(); reader.onload = () => update({ ...module, photo: { src: String(reader.result), visible: true, width: module.photo?.width ?? 25, height: module.photo?.height ?? 33, borderRadius: module.photo?.borderRadius ?? 2, objectPosition: module.photo?.objectPosition ?? '50% 50%' } }); reader.readAsDataURL(file); };
  return <>
    <label className="field-label" htmlFor="profile-name">姓名</label><input id="profile-name" className="text-input" value={getRichTextPlainText(module.name)} onChange={(event) => update({ ...module, name: richText(event.target.value) })} />
    <RichField label="意向岗位" content={module.targetRole} onChange={(targetRole) => update({ ...module, targetRole })} />
    <div className="field-grid"><label><span className="field-label">电话</span><input className="text-input" value={module.phone.value} onChange={(event) => update({ ...module, phone: { ...module.phone, value: event.target.value } })} /></label><label><span className="field-label">邮箱</span><input className="text-input" value={module.email.value} onChange={(event) => update({ ...module, email: { ...module.email, value: event.target.value } })} /></label></div>
    <div className="visibility-row"><label><input type="checkbox" checked={module.phone.visible} onChange={(event) => update({ ...module, phone: { ...module.phone, visible: event.target.checked } })} />显示电话</label><label><input type="checkbox" checked={module.email.visible} onChange={(event) => update({ ...module, email: { ...module.email, visible: event.target.checked } })} />显示邮箱</label></div>
    <h3 className="editor-subtitle">自定义字段</h3>{module.customFields.map((field) => <div className="custom-field-editor" key={field.id}><input aria-label="字段名称" className="text-input" value={field.label} onChange={(event) => update({ ...module, customFields: module.customFields.map((candidate) => candidate.id === field.id ? { ...candidate, label: event.target.value } : candidate) })} /><RichTextEditor ariaLabel={`${field.label}内容`} compact content={field.value} onChange={(value) => update({ ...module, customFields: module.customFields.map((candidate) => candidate.id === field.id ? { ...candidate, value } : candidate) })} /><button aria-label="删除自定义字段" onClick={() => update({ ...module, customFields: module.customFields.filter((candidate) => candidate.id !== field.id) })}><Trash2 size={13} /></button></div>)}
    <button className="inline-add" onClick={() => update({ ...module, customFields: [...module.customFields, { id: crypto.randomUUID(), label: '新字段', value: richText('内容'), visible: true }] })}><Plus size={15} />添加自定义字段</button>
    <h3 className="editor-subtitle">照片</h3><input aria-label="上传照片" type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => uploadPhoto(event.target.files?.[0])} />{module.photo && <div className="photo-controls"><label>宽度<input type="number" value={module.photo.width} onChange={(event) => update({ ...module, photo: { ...module.photo!, width: Number(event.target.value) } })} /></label><label>高度<input type="number" value={module.photo.height} onChange={(event) => update({ ...module, photo: { ...module.photo!, height: Number(event.target.value) } })} /></label><button onClick={() => update({ ...module, photo: undefined })}>删除照片</button></div>}
  </>;
}

export function ModuleEditor() {
  const module = useResumeStore((state) => state.resume.modules.find((candidate) => candidate.id === state.selectedModuleId));
  const updateModule = useResumeStore((state) => state.updateModule);
  if (!module) return <div className="empty-module-editor">选择一个模块开始编辑</div>;
  const update = (next: ResumeModule) => updateModule(module.id, () => next);
  return <section className="property-card"><div className="property-card-heading"><div><span className="eyebrow">SELECTED MODULE</span><h2>{module.title || '个人信息'}</h2></div></div>
    {module.type === 'profile' && <ProfileEditor module={module} update={update} />}
    {module.type === 'education' && <><SortableEntries items={module.entries} onChange={(entries) => update({ ...module, entries })} render={(entry: EducationEntry, index) => <SortableEntry key={entry.id} id={entry.id} label={`教育经历 ${index + 1}`} onDelete={() => update({ ...module, entries: module.entries.filter((candidate) => candidate.id !== entry.id) })}><div className="rich-field-grid"><RichField label="学校" content={entry.school} onChange={(school) => update({ ...module, entries: module.entries.map((candidate) => candidate.id === entry.id ? { ...candidate, school } : candidate) })} /><RichField label="学位" content={entry.degree} onChange={(degree) => update({ ...module, entries: module.entries.map((candidate) => candidate.id === entry.id ? { ...candidate, degree } : candidate) })} /><RichField label="专业" content={entry.major} onChange={(major) => update({ ...module, entries: module.entries.map((candidate) => candidate.id === entry.id ? { ...candidate, major } : candidate) })} /><RichField label="其他信息" content={entry.otherInfo} onChange={(otherInfo) => update({ ...module, entries: module.entries.map((candidate) => candidate.id === entry.id ? { ...candidate, otherInfo } : candidate) })} /></div><DateFields value={entry} onChange={(date) => update({ ...module, entries: module.entries.map((candidate) => candidate.id === entry.id ? { ...candidate, ...date } : candidate) })} /><ContentBlocksEditor blocks={entry.blocks} onChange={(blocks) => update({ ...module, entries: module.entries.map((candidate) => candidate.id === entry.id ? { ...candidate, blocks } : candidate) })} /></SortableEntry>} /><button className="inline-add" onClick={() => update({ ...module, entries: [...module.entries, { id: crypto.randomUUID(), school: richText('学校名称'), degree: richText('学历'), major: richText('专业'), startDate: '2024-09', current: true, blocks: [] }] })}><Plus size={15} />添加教育经历</button></>}
    {module.type === 'internship' && <><SortableEntries items={module.entries} onChange={(entries) => update({ ...module, entries })} render={(entry: InternshipEntry, index) => <SortableEntry key={entry.id} id={entry.id} label={`实习经历 ${index + 1}`} onDelete={() => update({ ...module, entries: module.entries.filter((candidate) => candidate.id !== entry.id) })}><div className="rich-field-grid"><RichField label="公司" content={entry.company} onChange={(company) => update({ ...module, entries: module.entries.map((candidate) => candidate.id === entry.id ? { ...candidate, company } : candidate) })} /><RichField label="岗位" content={entry.role} onChange={(role) => update({ ...module, entries: module.entries.map((candidate) => candidate.id === entry.id ? { ...candidate, role } : candidate) })} /><RichField label="其他信息" content={entry.otherInfo} onChange={(otherInfo) => update({ ...module, entries: module.entries.map((candidate) => candidate.id === entry.id ? { ...candidate, otherInfo } : candidate) })} /></div><DateFields value={entry} onChange={(date) => update({ ...module, entries: module.entries.map((candidate) => candidate.id === entry.id ? { ...candidate, ...date } : candidate) })} /><SortableEntries items={entry.projects} onChange={(projects) => update({ ...module, entries: module.entries.map((candidate) => candidate.id === entry.id ? { ...candidate, projects } : candidate) })} render={(project: ExperienceProject, projectIndex) => <ProjectEditor key={project.id} project={project} index={projectIndex} onChange={(next) => update({ ...module, entries: module.entries.map((candidate) => candidate.id === entry.id ? { ...candidate, projects: candidate.projects.map((value) => value.id === project.id ? next : value) } : candidate) })} onDelete={() => update({ ...module, entries: module.entries.map((candidate) => candidate.id === entry.id ? { ...candidate, projects: candidate.projects.filter((value) => value.id !== project.id) } : candidate) })} />} /><button className="inline-add" onClick={() => update({ ...module, entries: module.entries.map((candidate) => candidate.id === entry.id ? { ...candidate, projects: [...candidate.projects, { id: crypto.randomUUID(), name: richText('项目名称'), role: richText('职责'), blocks: [] }] } : candidate) })}><Plus size={14} />添加实习项目</button></SortableEntry>} /><button className="inline-add" onClick={() => update({ ...module, entries: [...module.entries, { id: crypto.randomUUID(), company: richText('公司名称'), role: richText('岗位'), current: true, projects: [] }] })}><Plus size={15} />添加实习经历</button></>}
    {module.type === 'project' && <><SortableEntries items={module.projects} onChange={(projects) => update({ ...module, projects })} render={(project: ExperienceProject, index) => <ProjectEditor key={project.id} project={project} index={index} onChange={(next) => update({ ...module, projects: module.projects.map((candidate) => candidate.id === project.id ? next : candidate) })} onDelete={() => update({ ...module, projects: module.projects.filter((candidate) => candidate.id !== project.id) })} />} /><button className="inline-add" onClick={() => update({ ...module, projects: [...module.projects, { id: crypto.randomUUID(), name: richText('项目名称'), role: richText('职责'), current: true, blocks: [] }] })}><Plus size={15} />添加项目</button></>}
    {module.type === 'free' && <><label className="field-label">模块标题</label><input className="text-input" value={module.title} onChange={(event) => update({ ...module, title: event.target.value })} /><ContentBlocksEditor blocks={module.blocks} onChange={(blocks) => update({ ...module, blocks })} /></>}
  </section>;
}
